mcap futures settlement
vegaprotocol/research pull request #40
Opened 2024-03-12 16:50 UTC by davidsiska-vega

2024-03-13 09:15 UTC, witgaw reviewed
LGTM, just some minor suggestions:

2024-03-13 09:15 UTC, witgaw commented on notes/mcap-futures-markets-settlement.md
> +The approach is modelled on Credit Default Swaps (CDS) which are derivatives that are valued based on the probability of a company defaulting. Payouts are triggered when a “credit event” occurs, as d
```suggestion
The approach is modelled on Credit Default Swaps (CDS) which are derivatives that are valued based on the probability of a company defaulting. Payouts are triggered when a “credit event” occurs, as defined by a set of explicit rules. Analogously, we define the concept of an “token launch” that can be similarly used to determine when and at what value to settle MCAP futures.
```

2024-03-18 12:58 UTC, TomMcL commented on notes/mcap-futures-markets-settlement.md
> +: The minimum amount of cumulative time over which a market meeting the liquidity and slippage thresholds must exist to trigger a succesful ***MCAP Valuation Algorithm*** calculation.
```suggestion
: The minimum amount of cumulative time over which a market meeting the liquidity and slippage thresholds must exist to trigger a successful ***MCAP Valuation Algorithm*** calculation.
```

2024-03-18 13:01 UTC, TomMcL reviewed
I wonder if it's worth adding a section about the possibility of a market amendment to align with actual number of tokens issued if it's announced?

2024-03-18 18:13 UTC, barnabee requested changes

2024-03-22 10:06 UTC, davidsiska-vega commented on notes/mcap-futures-markets-settlement.md
> +Conceptually, we need to define three things to enable fair and orderly settlement of an mcap futures market:
```suggestion
Conceptually, we need to define four things to enable fair and orderly settlement of an mcap futures market:
```

2024-03-22 10:19 UTC, davidsiska-vega commented on notes/mcap-futures-markets-settlement.md
> +Conceptually, we need to define three things to enable fair and orderly settlement of an mcap futures market:
Yea, fixed.

2024-03-22 10:19 UTC, davidsiska-vega commented on notes/mcap-futures-markets-settlement.md
> +`Inclusivity Threshold` (40.00%)
Changed.

2024-03-22 10:19 UTC, davidsiska-vega commented on notes/mcap-futures-markets-settlement.md
> +Once the token has launched and has been trading for `Minimum Trading Window` with sufficient `Liquidity Threshold` the valuation algorithm will calculate the MCAP as the time-weighted average price,
Re-wrote.

2024-03-22 10:19 UTC, davidsiska-vega commented on notes/mcap-futures-markets-settlement.md
> +`Minimum Trading Window` (48 hours)
Changed to a week.

2024-05-29 16:26 UTC, barnabee approved these changes

2024-09-26 12:52 UTC, merged